[package]
name = "ecc_calc"
version = "0.3.3"
authors = ["Todoroki <todoroki.auone@gmail.com>"]

[dependencies]
num = "0.1"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
simple_logger = "0.5"